const express = require('express');
const app = express();
const PORT = 8080;
const cors = require('cors');
const loignrouter = require('./router/loginRoute');
const registerRouter = require('./router/registerRouter');
const { errorHandlerMiddleware } = require('./middleware/errorhandler');
app.use(express.json());
app.use(cors('*'));
app.use('/login', loignrouter);
app.use('/register', registerRouter);
app.use(errorHandlerMiddleware);
app.listen(PORT, () => console.log(`app listening at http://localhost:${PORT}`));
